# Generated by Django 4.0.7 on 2025-10-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Key name')),
                ('kvalue', models.TextField(blank=True, default='', null=True, verbose_name='Key value')),
            ],
            options={
                'verbose_name_plural': 'Information Items',
            },
        ),
    ]
