"""
Django settings for istanbul project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
import posixpath
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# OLD: WRITABLE_DIR = os.path.abspath(os.path.join(BASE_DIR, "../../writable/database/"))
WRITABLE_DIR = os.path.abspath(os.path.join(BASE_DIR, "../writable/database/"))

if "d:" in WRITABLE_DIR.lower():
    # Need another string
    # OLD: WRITABLE_DIR = os.path.abspath(os.path.join(BASE_DIR, "../../../writable/database/"))
    WRITABLE_DIR = os.path.abspath(os.path.join(BASE_DIR, "../../writable/database/"))


MEDIA_DIR = os.path.abspath(os.path.join(WRITABLE_DIR, "../media/"))
MEDIA_ROOT = MEDIA_DIR
MEDIA_URL = '/media/'
XSENDFILE = config('XSENDFILE', True, cast=bool)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

APP_PREFIX = ""
USE_REDIS = False
ADMIN_SITE_URL = ""
if "d:" in WRITABLE_DIR.lower() or "c:" in WRITABLE_DIR.lower():
    APP_PREFIX = ""
    ADMIN_SITE_URL = '/'
    # No redis needed when running locally
    MEDIA_DIR = os.path.abspath(os.path.join(MEDIA_DIR, "istanbul"))
    MEDIA_ROOT = MEDIA_DIR
else:
    APP_PREFIX = ""
    ADMIN_SITE_URL = '/'
    USE_REDIS = True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =  config('SECRET_KEY')

ALLOWED_HOSTS = ['localhost', 'istanbul-su.rich.ru.nl', 'testserver']

# Caching
if USE_REDIS:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://127.0.0.1:7779/1",
            "TIMEOUT": None,
            "OPTIONS": { "CLIENT_CLASS": "django_redis.client.DefaultClient", }
            },
        "select2": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://127.0.0.1:7779/2",
            "TIMEOUT": None,
            "OPTIONS": { "CLIENT_CLASS": "django_redis.client.DefaultClient", }
            }
        }
    # Set the cache backend to select2
    SELECT2_CACHE_BACKEND = 'select2'
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'TIMEOUT': None,
        }
    }


# Application references
# https://docs.djangoproject.com/en/2.1/ref/settings/#std:setting-INSTALLED_APPS
INSTALLED_APPS = [
    # Add your apps here to enable them
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'accounts.apps.AccountsConfig',
	'installations.apps.InstallationsConfig',
	'utilities.apps.UtilitiesConfig',
	'easyaudit',
	'django_select2',
	'colorfield',
    'mapview',
    'basic',
    'cms',
]

# Middleware framework
# https://docs.djangoproject.com/en/2.1/topics/http/middleware/
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'easyaudit.middleware.easyaudit.EasyAuditMiddleware',
]

ROOT_URLCONF = 'istanbul.urls'

# Template configuration
# https://docs.djangoproject.com/en/2.1/topics/templates/
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'istanbul.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'NAME': os.path.join(WRITABLE_DIR, config('DB_NAME')),
        'TEST': {
            'NAME': os.path.join(WRITABLE_DIR, 'istanbul-test.db'),
            }
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'CET'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = posixpath.join(*(BASE_DIR.split(os.path.sep) + ['static']))

# Taken over from Martijn
SELECT2BOOTSTRAP = True
LOGIN_REDIRECT_URL = '/installations/home'
LOGOUT_REDIRECT_URL = '/accounts/login/'
	

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CSRF_TRUSTED_ORIGINS = ['https://istanbul-su.rich.ru.nl']

