# Generated by Django 4.0.5 on 2022-08-02 11:00

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import partial_date.partial_date
import utils.model_util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('start_date', partial_date.partial_date.PartialDateField(blank=True, null=True)),
                ('end_date', partial_date.partial_date.PartialDateField(blank=True, null=True)),
                ('date_comments', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('comments', models.TextField(default='')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(default='')),
                ('comments', models.TextField(default='')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='IMAGES/')),
                ('maker', models.CharField(blank=True, max_length=300, null=True)),
                ('year', partial_date.partial_date.PartialDateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('current_location', models.CharField(blank=True, max_length=300, null=True)),
                ('collection', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('comments', models.TextField(default='')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('ottoman_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('english_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('turkish_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(default='')),
                ('comments', models.TextField(default='')),
                ('still_exists', models.BooleanField(blank=True, null=True)),
                ('events', models.ManyToManyField(blank=True, default=None, to='installations.event')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='InstallationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(default='')),
                ('comments', models.TextField(default='')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(default='')),
                ('comments', models.TextField(default='')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('editor', models.CharField(blank=True, max_length=300, null=True)),
                ('publisher', models.CharField(blank=True, max_length=300, null=True)),
                ('place', models.CharField(blank=True, max_length=300, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('journal', models.CharField(blank=True, max_length=300, null=True)),
                ('volume', models.CharField(blank=True, max_length=100, null=True)),
                ('page_numbers', models.CharField(blank=True, max_length=100, null=True)),
                ('issue', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(default='')),
                ('comments', models.TextField(default='')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(default='')),
                ('comments', models.TextField(default='')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(default='')),
                ('comments', models.TextField(default='')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('line_thickness', models.IntegerField(blank=True, default=2, null=True)),
                ('fill_opacity', models.FloatField(blank=True, default=0.3, null=True)),
                ('line_opacity', models.FloatField(blank=True, default=0.3, null=True)),
                ('dashed', models.BooleanField(default=False)),
                ('z_index', models.IntegerField(blank=True, default=0, null=True)),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('ottoman_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('english_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('turkish_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(default='')),
                ('comments', models.TextField(default='')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='TextType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='SystemInstallationRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', partial_date.partial_date.PartialDateField(blank=True, null=True)),
                ('end_date', partial_date.partial_date.PartialDateField(blank=True, null=True)),
                ('description', models.TextField(default='')),
                ('comments', models.TextField(default='')),
                ('is_part_of', models.BooleanField(blank=True, null=True)),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.installation')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.system')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('birth_year', partial_date.partial_date.PartialDateField(blank=True, null=True)),
                ('death_year', partial_date.partial_date.PartialDateField(blank=True, null=True)),
                ('start_reign', partial_date.partial_date.PartialDateField(blank=True, null=True)),
                ('end_reign', partial_date.partial_date.PartialDateField(blank=True, null=True)),
                ('description', models.TextField(default='')),
                ('comments', models.TextField(default='')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.gender')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.religion')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('ottoman_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('english_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('turkish_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(default='')),
                ('comments', models.TextField(default='')),
                ('institution_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.institutiontype')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.religion')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.AddField(
            model_name='installation',
            name='installation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.installationtype'),
        ),
        migrations.AddField(
            model_name='installation',
            name='purposes',
            field=models.ManyToManyField(blank=True, default=None, to='installations.purpose'),
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('geojson', models.FileField(blank=True, null=True, upload_to='GEOJSON/')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.style')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='EventPersonRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.event')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.person')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.eventrole')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='EventLiteratureRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(default='')),
                ('text_file', models.FileField(blank=True, null=True, upload_to='FILES/')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.event')),
                ('literature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.literature')),
                ('text_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.texttype')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='EventInstitutionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.event')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.institution')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.eventrole')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.eventtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='figure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.figure'),
        ),
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, to='installations.image'),
        ),
    ]
