# Generated by Django 4.0.7 on 2022-08-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='literature',
            old_name='description',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='installation',
            name='english_name',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='english_name',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='literature',
            name='code',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='religion',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='english_name',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'start_date', 'end_date')},
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('name', 'birth_year', 'death_year')},
        ),
    ]
