# Generated by Django 4.0.7 on 2022-11-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0003_installation_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='literature',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
