# Generated by Django 4.0.7 on 2024-10-30 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0004_literature_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpersonrelation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventpersonrelations', to='installations.event'),
        ),
        migrations.AlterField(
            model_name='eventpersonrelation',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventpersonrelations', to='installations.person'),
        ),
        migrations.AlterField(
            model_name='eventpersonrelation',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventpersonrelations', to='installations.eventrole'),
        ),
    ]
