# Generated by Django 4.0.7 on 2024-10-30 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0005_alter_eventpersonrelation_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('x_coordinate', models.CharField(default='unknown', max_length=255, verbose_name='X-coordinate (latitude)')),
                ('y_coordinate', models.CharField(default='unknown', max_length=255, verbose_name='Y-coordinate (longitude)')),
                ('loctype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loctype_locations', to='installations.loctype')),
            ],
        ),
    ]
