# Generated by Django 4.0.7 on 2024-11-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0007_installation_location_system_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='images',
        ),
    ]
