# Generated by Django 4.0.7 on 2024-11-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0008_remove_event_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='image',
            name='longitude',
        ),
    ]
