# Generated by Django 4.0.7 on 2024-11-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0009_remove_image_latitude_remove_image_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='geojson',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
