# Generated by Django 4.0.7 on 2025-04-23 09:01

from django.db import migrations, models
import django.db.models.deletion
import utils.model_util


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0013_imagetype_image_itype'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(default='')),
                ('comments', models.TextField(default='')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.AddField(
            model_name='installation',
            name='installation_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.installationstatus'),
        ),
    ]
