# Generated by Django 4.0.7 on 2025-09-04 07:18

from django.db import migrations, models
import django.db.models.deletion
import utils.model_util


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0014_installationstatus_installation_installation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInstallationRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=-1, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventinstallation_relations', to='installations.event')),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventinstallation_relations', to='installations.installation')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
    ]
