# Generated by Django 4.0.7 on 2025-09-04 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0015_eventinstallationrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinstallationrelation',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventinstallation_relations', to='installations.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventinstallationrelation',
            name='installation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventinstallation_relations', to='installations.installation'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='installation',
            name='events',
        ),
        migrations.AddField(
            model_name='installation',
            name='events',
            field=models.ManyToManyField(blank=True, default=None, through='installations.EventInstallationRelation', to='installations.event'),
        ),
    ]
