# Generated by Django 4.0.7 on 2025-09-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0016_alter_eventinstallationrelation_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='events',
            field=models.ManyToManyField(through='installations.EventInstallationRelation', to='installations.event'),
        ),
    ]
