# Generated by Django 4.0.7 on 2025-09-04 12:49

from django.db import migrations, models
import django.db.models.deletion
import utils.model_util


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0017_alter_installation_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_extlinks', to='installations.installation')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
    ]
