# Generated by Django 4.0.7 on 2025-09-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0018_externallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='simple_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='simple_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='simple_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
