# Generated by Django 4.0.7 on 2025-10-13 07:02

from django.db import migrations, models
import django.db.models.deletion
import utils.model_util


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0019_installation_simple_name_institution_simple_name_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Old table name from checking with sqlmigrate, new table
                # name from AuthorBook._meta.db_table.
                migrations.RunSQL(
                    sql="ALTER TABLE installations_installation_images RENAME TO installations_imageinstallationrelation",
                    reverse_sql="ALTER TABLE installations_imageinstallationrelation RENAME TO installations_installation_images",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ImageInstallationRelation",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "image",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                to="installations.Image",
                            ),
                        ),
                        (
                            "installation",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                to="installations.Installation",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="installation",
                    name="images",
                    field=models.ManyToManyField(
                        to="installations.Image",
                        through="installations.ImageInstallationRelation",
                    ),
                ),
            ],
        ),


    ]
