# Generated by Django 4.0.7 on 2025-10-13 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0020_installationimagerelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinstallationrelation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imageinstallationrelation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageinstallation_relations', to='installations.image'),
        ),
        migrations.AlterField(
            model_name='imageinstallationrelation',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageinstallation_relations', to='installations.installation'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, through='installations.ImageInstallationRelation', to='installations.image'),
        ),
    ]
