# Generated by Django 4.0.7 on 2025-10-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0021_alter_imageinstallationrelation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageinstallationrelation',
            name='order',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
