# Generated by Django 4.0.7 on 2025-10-15 12:58

from django.db import migrations, models
import utils.model_util


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0022_imageinstallationrelation_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(default='')),
                ('comments', models.TextField(default='')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
    ]
