# Generated by Django 4.0.7 on 2025-10-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0023_datetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.datetype'),
        ),
    ]
