# Generated by Django 4.0.7 on 2026-07-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0024_event_end_date_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='instcount',
            field=models.IntegerField(default=0),
        ),
    ]
