# Generated by Django 4.0.7 on 2026-07-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0025_purpose_instcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='literature',
            name='eventcount',
            field=models.IntegerField(default=0),
        ),
    ]
