# Generated by Django 4.0.7 on 2026-07-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0026_literature_eventcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='srch_english_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
