# Generated by Django 4.0.7 on 2026-07-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0027_installation_srch_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrole',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='eventrole',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='texttype',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='texttype',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
