# Generated by Django 4.0.7 on 2026-07-16 12:19

from django.db import migrations, models
import django.db.models.deletion
import utils.model_util


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0028_eventrole_comments_eventrole_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSystemRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=-1, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesystem_relations', to='installations.image')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.CreateModel(
            name='SystemLiteratureRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(default='')),
                ('text_file', models.FileField(blank=True, null=True, upload_to='FILES/')),
                ('literature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.literature')),
            ],
            bases=(models.Model, utils.model_util.info),
        ),
        migrations.AddField(
            model_name='system',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, through='installations.ImageSystemRelation', to='installations.image'),
        ),
        migrations.AddField(
            model_name='system',
            name='litrefs',
            field=models.ManyToManyField(blank=True, default=None, through='installations.SystemLiteratureRelation', to='installations.literature'),
        ),
        migrations.AddField(
            model_name='systemliteraturerelation',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.system'),
        ),
        migrations.AddField(
            model_name='systemliteraturerelation',
            name='text_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.texttype'),
        ),
        migrations.AddField(
            model_name='imagesystemrelation',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesystem_relations', to='installations.system'),
        ),
    ]
